# Generated by Django 4.2.3 on 2023-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_task_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="position",
            field=models.IntegerField(
                db_index=True, null=True, unique=True, verbose_name="Position in list"
            ),
        ),
    ]
